# Jekyll (GitHub Pages) Configuration

base_url: https://kwdstudio.se
assets_base_url: ""
google_analytics_id: UA-96783273-1
permalink: /:path
collections:
  cases:
    output: true
    permalink: /case/:path
  pages:
    output: true
    permalink: /:path
  clients:
    output: false
  co_workers:
    output: false
exclude:
  - hooks
  - src
  - package.json
  - package-lock.json
  - webpack.config.js
  - node_modules
  - README.md
  - Gemfile
  - Gemfile.lock
