# Jekyll (GitHub Pages) Configuration

assets_base_url: ""
collections:
  - clients
exclude:
  - hooks
  - src
  - package.json
  - package-lock.json
  - webpack.config.js
  - node_modules
  - README.md
  - Gemfile
  - Gemfile.lock
