# Jekyll (GitHub Pages) Configuration

base_url: https://kwdstudio.se
assets_base_url: ""
analytics: true
permalink: /:path
collections:
  cases:
    output: true
    permalink: /case/:path
  jobs:
    output: true
    permalink: /jobb/:path
  pages:
    output: true
    permalink: /:path
  clients:
    output: false
  co_workers:
    output: false
exclude:
  - hooks
  - src
  - package.json
  - package-lock.json
  - webpack.config.js
  - node_modules
  - README.md
  - Gemfile
  - Gemfile.lock
plugins:
  - jekyll-redirect-from
