# Jekyll (GitHub Pages) Configuration

assets_base_url: ""
google_analytics_id: UA-96783273-1
collections:
  cases:
    output: true
  clients:
    output: false
  co_workers:
    output: false
exclude:
  - hooks
  - src
  - package.json
  - package-lock.json
  - webpack.config.js
  - node_modules
  - README.md
  - Gemfile
  - Gemfile.lock
